// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
'use client'
import { createTheme, ThemeProvider } from '@mui/material/styles';
import theme from "@/themes/WeddingTheme";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
