# Generated by Django 5.0.7 on 2024-08-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('attending', models.BooleanField()),
                ('message', models.CharField(max_length=1000)),
                ('hotel_needed', models.BooleanField()),
            ],
        ),
    ]
